/**
 * 1000 culturally-appropriate names mapped to countries for activity notifications.
 * ~67 names per country across 15 major developed nations.
 */

export const NAMES_BY_COUNTRY: Record<string, string[]> = {
    "United States": [
        "James T.", "Emily R.", "Michael S.", "Sarah K.", "David L.", "Jessica M.",
        "Robert W.", "Ashley B.", "William H.", "Amanda C.", "Christopher D.", "Megan P.",
        "Daniel F.", "Lauren G.", "Matthew J.", "Stephanie N.", "Andrew V.", "Rachel A.",
        "Joshua E.", "Nicole Z.", "Brandon Q.", "Samantha W.", "Justin H.", "Kayla R.",
        "Ryan M.", "Brittany S.", "Tyler L.", "Courtney D.", "Kevin B.", "Christina P.",
        "Nathan F.", "Rebecca J.", "Aaron G.", "Heather K.", "Patrick V.", "Michelle T.",
        "Sean C.", "Jennifer N.", "Zachary A.", "Melissa E.", "Derek Q.", "Danielle W.",
        "Kyle H.", "Amber R.", "Eric M.", "Tiffany S.", "Brian L.", "Elizabeth D.",
        "Gregory B.", "Victoria P.", "Marcus F.", "Allison J.", "Scott G.", "Hannah K.",
        "Trevor V.", "Morgan T.", "Cody C.", "Alexis N.", "Dustin A.", "Taylor E.",
        "Blake Q.", "Madison W.", "Cameron H.", "Savannah R.", "Jordan M.", "Olivia S.",
        "Chase L.",
    ],
    "United Kingdom": [
        "Oliver W.", "Charlotte H.", "Harry M.", "Amelia T.", "George B.", "Sophie R.",
        "Jack S.", "Emily K.", "Thomas D.", "Isla P.", "James F.", "Grace J.",
        "William G.", "Olivia V.", "Henry C.", "Mia N.", "Edward A.", "Lily E.",
        "Charles Q.", "Freya W.", "Daniel H.", "Poppy R.", "Samuel M.", "Ella S.",
        "Joseph L.", "Ruby D.", "Alexander B.", "Daisy P.", "Arthur F.", "Rosie J.",
        "Benjamin G.", "Florence K.", "Oscar V.", "Evie T.", "Leo C.", "Alice N.",
        "Freddie A.", "Sienna E.", "Archie Q.", "Isabella W.", "Max H.", "Millie R.",
        "Alfie M.", "Phoebe S.", "Noah L.", "Chloe D.", "Ethan B.", "Lucy P.",
        "Jacob F.", "Matilda J.", "Logan G.", "Willow K.", "Isaac V.", "Ava T.",
        "Theo C.", "Imogen N.", "Lucas A.", "Jessica E.", "Sebastian Q.", "Eleanor W.",
        "Finley H.", "Abigail R.", "Adam M.", "Scarlett S.", "Harrison L.", "Hannah D.",
        "Callum B.",
    ],
    "Canada": [
        "Liam P.", "Emma T.", "Noah R.", "Olivia M.", "Ethan S.", "Ava K.",
        "Lucas D.", "Sophia B.", "Mason F.", "Isabella J.", "Logan G.", "Mia V.",
        "Alexander C.", "Charlotte N.", "Benjamin A.", "Amelia E.", "James Q.", "Harper W.",
        "William H.", "Evelyn R.", "Daniel M.", "Abigail S.", "Jackson L.", "Emily D.",
        "Sebastian B.", "Ella P.", "Aiden F.", "Elizabeth J.", "Matthew G.", "Sofia K.",
        "Samuel V.", "Avery T.", "David C.", "Scarlett N.", "Joseph A.", "Grace E.",
        "Owen Q.", "Chloe W.", "Dylan H.", "Victoria R.", "Luke M.", "Riley S.",
        "Gabriel L.", "Aria D.", "Anthony B.", "Lily P.", "Isaac F.", "Aubrey J.",
        "Jayden G.", "Zoey K.", "Elijah V.", "Hannah T.", "Nathan C.", "Layla N.",
        "Caleb A.", "Nora E.", "Ryan Q.", "Lillian W.", "Adrian H.", "Addison R.",
        "Connor M.", "Ellie S.", "Aaron L.", "Stella D.", "Colton B.", "Natalie P.",
        "Hunter F.",
    ],
    Germany: [
        "Lukas M.", "Hannah S.", "Leon W.", "Emma K.", "Maximilian B.", "Mia R.",
        "Felix T.", "Sophia D.", "Paul F.", "Marie J.", "Jonas G.", "Anna V.",
        "Elias C.", "Emilia N.", "Noah A.", "Lina E.", "Ben Q.", "Lea W.",
        "Finn H.", "Clara R.", "Moritz M.", "Johanna S.", "Jan L.", "Laura D.",
        "Tim B.", "Sarah P.", "Niklas F.", "Lisa J.", "David G.", "Lena K.",
        "Alexander V.", "Julia T.", "Tobias C.", "Katharina N.", "Sebastian A.", "Nina E.",
        "Philipp Q.", "Jana W.", "Marcel H.", "Amelie R.", "Florian M.", "Nele S.",
        "Daniel L.", "Maja D.", "Matthias B.", "Charlotte P.", "Stefan F.", "Frieda J.",
        "Christian G.", "Greta K.", "Andreas V.", "Ida T.", "Thomas C.", "Ella N.",
        "Michael A.", "Mila E.", "Patrick Q.", "Luise W.", "Simon H.", "Theresa R.",
        "Dominik M.", "Antonia S.", "Markus L.", "Carla D.", "Oliver B.", "Helena P.",
        "Robert F.",
    ],
    France: [
        "Lucas M.", "Emma T.", "Hugo R.", "Léa S.", "Louis K.", "Manon D.",
        "Gabriel B.", "Chloé F.", "Raphaël J.", "Inès G.", "Arthur V.", "Jade C.",
        "Jules N.", "Louise A.", "Adam E.", "Alice Q.", "Léo W.", "Lina H.",
        "Nathan R.", "Rose M.", "Théo S.", "Ambre L.", "Ethan D.", "Anna B.",
        "Noah P.", "Mia F.", "Tom J.", "Léna G.", "Maxime K.", "Julia V.",
        "Sacha T.", "Eva C.", "Antoine N.", "Sarah A.", "Paul E.", "Zoé Q.",
        "Mathis W.", "Camille H.", "Alexandre R.", "Clara M.", "Pierre S.", "Juliette L.",
        "Valentin D.", "Margot B.", "Thomas P.", "Pauline F.", "Nicolas J.", "Marie G.",
        "Clément K.", "Charlotte V.", "Baptiste T.", "Anaïs C.", "Romain N.", "Océane A.",
        "Julien E.", "Victoire Q.", "Marc W.", "Agathe H.", "Olivier R.", "Sophie M.",
        "François S.", "Élise L.", "Laurent D.", "Mathilde B.", "Éric P.", "Céline F.",
        "Philippe J.",
    ],
    Australia: [
        "Jack M.", "Charlotte T.", "Oliver R.", "Amelia S.", "William K.", "Olivia D.",
        "Noah B.", "Isla F.", "Thomas J.", "Ava G.", "James V.", "Mia C.",
        "Ethan N.", "Grace A.", "Lucas E.", "Sophie Q.", "Liam W.", "Emily H.",
        "Cooper R.", "Chloe M.", "Henry S.", "Ella L.", "Archer D.", "Ruby B.",
        "Mason P.", "Lily F.", "Charlie J.", "Harper G.", "Harrison K.", "Zoe V.",
        "Hudson T.", "Sienna C.", "Leo N.", "Willow A.", "Max E.", "Ivy Q.",
        "Samuel W.", "Poppy H.", "Alexander R.", "Evie M.", "Ryan S.", "Matilda L.",
        "Benjamin D.", "Phoebe B.", "Daniel P.", "Scarlett F.", "Patrick J.", "Lucy G.",
        "Lachlan K.", "Abigail V.", "Mitchell T.", "Hannah C.", "Jayden N.", "Ellie A.",
        "Blake E.", "Audrey Q.", "Connor W.", "Aria H.", "Riley R.", "Savannah M.",
        "Finn S.", "Stella L.", "Dylan D.", "Layla B.", "Kai P.", "Mackenzie F.",
        "Brodie J.",
    ],
    Japan: [
        "Haruto T.", "Yui S.", "Sota M.", "Hina K.", "Yuto R.", "Sakura D.",
        "Riku B.", "Aoi F.", "Haruki J.", "Mio G.", "Kaito V.", "Rin C.",
        "Asahi N.", "Yuna A.", "Minato E.", "Koharu Q.", "Ren W.", "Akari H.",
        "Hiroto R.", "Mei M.", "Takumi S.", "Misaki L.", "Sora D.", "Honoka B.",
        "Daiki P.", "Nanami F.", "Ryota J.", "Miyu G.", "Kento K.", "Riko V.",
        "Yuki T.", "Haruka C.", "Hayato N.", "Yuzuki A.", "Shota E.", "Kokona Q.",
        "Kenji W.", "Mana H.", "Tatsuya R.", "Natsuki M.", "Ryo S.", "Hinata L.",
        "Naoki D.", "Saki B.", "Kazuki P.", "Ayaka F.", "Daisuke J.", "Kaede G.",
        "Shun K.", "Shiori V.", "Akira T.", "Kana C.", "Masato N.", "Rena A.",
        "Taro E.", "Yuki Q.", "Koji W.", "Mayu H.", "Hideo R.", "Emi M.",
        "Ryusei S.", "Nana L.", "Shin D.", "Ai B.", "Yuji P.", "Chika F.",
        "Kenichi J.",
    ],
    Switzerland: [
        "Luca M.", "Mia T.", "Noah R.", "Emma S.", "Leon K.", "Lena D.",
        "David B.", "Anna F.", "Samuel J.", "Sofia G.", "Elias V.", "Laura C.",
        "Jonas N.", "Lea A.", "Tim E.", "Sara Q.", "Nico W.", "Elena H.",
        "Jan R.", "Julia M.", "Finn S.", "Lina L.", "Gabriel D.", "Nina B.",
        "Alexander P.", "Clara F.", "Benjamin J.", "Alina G.", "Matteo K.", "Nora V.",
        "Rafael T.", "Amelie C.", "Simon N.", "Hannah A.", "Lukas E.", "Chiara Q.",
        "Fabian W.", "Valentina H.", "Marc R.", "Emilia M.", "Patrick S.", "Leonie L.",
        "Thomas D.", "Sophia B.", "Daniel P.", "Marie F.", "Michael J.", "Charlotte G.",
        "Andreas K.", "Ella V.", "Stefan T.", "Giulia C.", "Christian N.", "Fiona A.",
        "Dominik E.", "Lisa Q.", "Florian W.", "Zoe H.", "Marco R.", "Olivia M.",
        "Roman S.", "Isabel L.", "Tobias D.", "Ronja B.", "Oliver P.", "Jana F.",
        "Adrian J.",
    ],
    Netherlands: [
        "Daan M.", "Emma T.", "Sem R.", "Julia S.", "Lucas K.", "Sophie D.",
        "Liam B.", "Tess F.", "Noah J.", "Anna G.", "Jesse V.", "Lotte C.",
        "Milan N.", "Sara A.", "Finn E.", "Eva Q.", "Luuk W.", "Fleur H.",
        "Bram R.", "Noor M.", "Max S.", "Isa L.", "Lars D.", "Sanne B.",
        "Tim P.", "Lisa F.", "Thomas J.", "Laura G.", "Thijs K.", "Lieke V.",
        "Ruben T.", "Mila C.", "Stijn N.", "Amber A.", "Jasper E.", "Lynn Q.",
        "Niels W.", "Roos H.", "Daniël R.", "Femke M.", "Joost S.", "Nina L.",
        "Bas D.", "Iris B.", "Pieter P.", "Eline F.", "Rick J.", "Naomi G.",
        "Koen K.", "Charlotte V.", "Sander T.", "Anne C.", "Wouter N.", "Maria A.",
        "Tom E.", "Hannah Q.", "Hugo W.", "Maud H.", "Robin R.", "Lara M.",
        "Jelle S.", "Vera L.", "Timo D.", "Silke B.", "Mark P.", "Renske F.",
        "Stefan J.",
    ],
    Sweden: [
        "Oscar M.", "Astrid T.", "William R.", "Alice S.", "Lucas K.", "Ella D.",
        "Hugo B.", "Alma F.", "Liam J.", "Maja G.", "Oliver V.", "Ebba C.",
        "Elias N.", "Olivia A.", "Alexander E.", "Saga Q.", "Noah W.", "Freja H.",
        "Viktor R.", "Wilma M.", "Erik S.", "Elsa L.", "Emil D.", "Agnes B.",
        "Leo P.", "Julia F.", "Axel J.", "Linnéa G.", "Filip K.", "Klara V.",
        "Adam T.", "Molly C.", "Isak N.", "Vera A.", "Ludvig E.", "Elin Q.",
        "Theo W.", "Ida H.", "Arvid R.", "Ellen M.", "Nils S.", "Hanna L.",
        "Anton D.", "Nora B.", "Gustav P.", "Signe F.", "Karl J.", "Emilia G.",
        "Albin K.", "Tuva V.", "Edvin T.", "Tilda C.", "Olle N.", "Selma A.",
        "Simon E.", "Alva Q.", "Johannes W.", "Lova H.", "Rasmus R.", "Tyra M.",
        "Felix S.", "Meja L.", "David D.", "Sigrid B.", "Henrik P.", "Lovisa F.",
        "Mattias J.",
    ],
    Singapore: [
        "Wei Ming T.", "Hui Ling S.", "Jun Hao R.", "Xin Yi M.", "Zhi Wei K.",
        "Mei Ling D.", "Jia Jun B.", "Shu Min F.", "Yi Hao J.", "Li Ting G.",
        "Kai Wen V.", "Jia Yi C.", "Jun Jie N.", "Xin Hui A.", "Zhi Hao E.",
        "Yu Xuan Q.", "Jia Le W.", "Hui Min H.", "Wei Jie R.", "Shu Ting M.",
        "Ming Hao S.", "Jia Xin L.", "Kai Jun D.", "Xin Ying B.", "Zhi Jun P.",
        "Hui Shan F.", "Yi Xuan J.", "Li Wei G.", "Jun Wei K.", "Mei Xin V.",
        "Raj K.", "Priya M.", "Arjun S.", "Lakshmi T.", "Vikram R.", "Ananya D.",
        "Arun B.", "Deepa F.", "Ravi J.", "Kavitha G.", "Suresh V.", "Divya C.",
        "Ahmad N.", "Fatimah A.", "Hassan E.", "Nurul Q.", "Ismail W.", "Siti H.",
        "Ibrahim R.", "Aisyah M.", "Daniel S.", "Rachel L.", "Marcus D.", "Amanda B.",
        "Jason P.", "Cheryl F.", "Ryan J.", "Michelle G.", "Kevin K.", "Nicole V.",
        "Timothy T.", "Sarah C.", "Adrian N.", "Emily A.", "Brandon E.", "Chloe Q.",
        "Jonathan W.",
    ],
    "South Korea": [
        "Minjun K.", "Soyeon L.", "Jihoon P.", "Jiwon C.", "Seojun H.", "Yuna K.",
        "Jimin L.", "Minji P.", "Hyunwoo C.", "Soojin H.", "Junhyuk K.", "Eunji L.",
        "Dongwook P.", "Hayoung C.", "Taeyang H.", "Yerin K.", "Sungmin L.", "Dahyun P.",
        "Woojin C.", "Chaewon H.", "Jinwoo K.", "Soeun L.", "Kyungho P.", "Nayeon C.",
        "Hyunjin H.", "Jiyoung K.", "Sangwoo L.", "Subin P.", "Minseok C.", "Haeun H.",
        "Jaehyun K.", "Yujin L.", "Seungho P.", "Jisoo C.", "Taehyung H.", "Somin K.",
        "Youngho L.", "Eunbi P.", "Siwoo C.", "Yeonhee H.", "Dohyun K.", "Areum L.",
        "Junho P.", "Mirae C.", "Sungjae H.", "Boyoung K.", "Insung L.", "Gaeun P.",
        "Chanwoo C.", "Seoyoung H.", "Jaemin K.", "Jieun L.", "Myungho P.", "Hana C.",
        "Yoonho H.", "Yeseo K.", "Gunwoo L.", "Chaerin P.", "Dongmin C.", "Sua H.",
        "Hansol K.", "Jihye L.", "Seokjin P.", "Naeun C.", "Taewoo H.", "Minju K.",
        "Byungho L.",
    ],
    Norway: [
        "Emil M.", "Nora T.", "Jakob R.", "Emma S.", "Oliver K.", "Ella D.",
        "Filip B.", "Maja F.", "Henrik J.", "Sofie G.", "Magnus V.", "Olivia C.",
        "Theodor N.", "Ingrid A.", "William E.", "Amalie Q.", "Aksel W.", "Leah H.",
        "Kasper R.", "Sara M.", "Isak S.", "Thea L.", "Mathias D.", "Ida B.",
        "Tobias P.", "Emilie F.", "Sebastian J.", "Astrid G.", "Sander K.", "Mia V.",
        "Jonas T.", "Elise C.", "Adrian N.", "Frida A.", "Andreas E.", "Julie Q.",
        "Markus W.", "Hanna H.", "Kristian R.", "Vilde M.", "Lars S.", "Sigrid L.",
        "Eirik D.", "Linnea B.", "Håkon P.", "Aurora F.", "Oskar J.", "Hedda G.",
        "Erlend K.", "Tuva V.", "Mats T.", "Tiril C.", "Simen N.", "Maren A.",
        "Vegard E.", "Selma Q.", "Thomas W.", "Alma H.", "Nikolai R.", "Oda M.",
        "Petter S.", "Martine L.", "Bjørn D.", "Live B.", "Knut P.", "Helene F.",
        "Sindre J.",
    ],
    Denmark: [
        "Noah M.", "Freja T.", "Oscar R.", "Ida S.", "William K.", "Clara D.",
        "Lucas B.", "Alma F.", "Victor J.", "Emma G.", "Oliver V.", "Sofie C.",
        "Carl N.", "Anna A.", "Malthe E.", "Laura Q.", "Emil W.", "Ella H.",
        "Frederik R.", "Nora M.", "Magnus S.", "Maja L.", "Mikkel D.", "Olivia B.",
        "Sebastian P.", "Karla F.", "Rasmus J.", "Agnes G.", "Christian K.", "Astrid V.",
        "Nikolaj T.", "Frida C.", "Mathias N.", "Saga A.", "Marcus E.", "Josefine Q.",
        "Tobias W.", "Alberte H.", "Alexander R.", "Isabella M.", "Henrik S.", "Sofia L.",
        "Kasper D.", "Ellen B.", "Mads P.", "Esther F.", "Anders J.", "Vilma G.",
        "Søren K.", "Marie V.", "Lars T.", "Emilie C.", "Peter N.", "Julie A.",
        "Thomas E.", "Rosa Q.", "Jakob W.", "Liva H.", "Jonas R.", "Fie M.",
        "Simon S.", "Andrea L.", "Erik D.", "Lea B.", "Christoffer P.", "Thea F.",
        "Jens J.",
    ],
    Ireland: [
        "Conor M.", "Aoife T.", "Sean R.", "Saoirse S.", "Liam K.", "Ciara D.",
        "Jack B.", "Niamh F.", "James J.", "Emma G.", "Cian V.", "Aisling C.",
        "Oisín N.", "Caoimhe A.", "Fionn E.", "Róisín Q.", "Darragh W.", "Siobhán H.",
        "Eoin R.", "Orla M.", "Patrick S.", "Maeve L.", "Ryan D.", "Sinéad B.",
        "Tadhg P.", "Clodagh F.", "Cillian J.", "Éabha G.", "Dylan K.", "Sorcha V.",
        "Shane T.", "Molly C.", "Adam N.", "Grace A.", "Luke E.", "Holly Q.",
        "Callum W.", "Sarah H.", "Aaron R.", "Hannah M.", "Cathal S.", "Emily L.",
        "Daniel D.", "Sophie B.", "Declan P.", "Lily F.", "Kevin J.", "Ella G.",
        "Brian K.", "Ruby V.", "Gavin T.", "Megan C.", "Niall N.", "Kate A.",
        "Colm E.", "Leah Q.", "Brendan W.", "Chloe H.", "Ronan R.", "Alice M.",
        "Fergus S.", "Fiona L.", "Pádraig D.", "Anna B.", "Donal P.", "Jessica F.",
        "Kieran J.",
    ],
};

/** Flat list of all country names */
export const COUNTRY_NAMES = Object.keys(NAMES_BY_COUNTRY);

/** Total names count (for reference): ~1005 */
